version: "3.6"

services:
  postgres:
    image: postgres:12.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: north
      POSTGRES_PASSWORD: password
      POSTGRES_DB: north

  hasura:
    image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    volumes:
      - ./metadata:/hasura-metadata
      - ./migrations:/hasura-migrations
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://north:password@postgres:5432/north"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
      HASURA_GRAPHQL_ADMIN_SECRET: admin

volumes:
  postgres_data:
